# Generated by Django 5.0.1 on 2025-11-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_request_document_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='response_document',
            field=models.FileField(blank=True, null=True, upload_to='quotation_responses/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('out_of_stock', 'Out of Stock'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
