"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "en" | "am"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      if (value && typeof value === "object") {
        value = value[k]
      } else {
        return key // Return key if translation not found
      }
    }

    return typeof value === "string" ? value : key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// Translation object
const translations = {
  en: {
    common: {
      home: "Home",
      about: "About Us",
      contact: "Contact",
      login: "Login",
      register: "Register",
      logout: "Logout",
      search: "Search",
      categories: "Categories",
      products: "Products",
      dashboard: "Dashboard",
      favorites: "Favorites",
      settings: "Settings",
      profile: "Profile",
      language: "Language",
      english: "English",
      amharic: "አማርኛ",
      welcome: "Welcome to Zutali Conmart",
      loading: "Loading...",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      view: "View",
      submit: "Submit",
      back: "Back",
      next: "Next",
      previous: "Previous",
      close: "Close",
    },
    header: {
      searchPlaceholder: "Search for construction materials...",
      loginRegister: "Login / Register",
      asUser: "As User/Purchaser",
      asOwner: "As Product Owner",
    },
    home: {
      heroTitle: "Build Your Dreams with",
      heroTitleHighlight: "Quality Materials",
      heroSubtitle:
        "Ethiopia's premier marketplace connecting builders, contractors, and suppliers. Find verified suppliers, compare prices, and get quotations for all your construction needs.",
      browseMaterials: "Browse Materials",
      becomeSupplier: "Become a Supplier",
      verifiedSuppliers: "Verified Suppliers",
      verifiedSuppliersDesc: "All product owners are verified with proper business documentation",
      qualityAssured: "Quality Assured",
      qualityAssuredDesc: "Only sustainable and quality construction materials listed",
      deliveryOptions: "Delivery Options",
      deliveryOptionsDesc: "Many suppliers offer delivery services to your location",
      bestPrices: "Best Prices",
      bestPricesDesc: "Compare prices from multiple suppliers to get the best deal",
      browseByCategory: "Browse by Category",
      browseByCategoryDesc: "Explore our wide range of construction materials organized by category",
      viewAllCategories: "View All Categories",
      readyToStart: "Ready to Start Your Project?",
      readyToStartDesc: "Join thousands of builders and contractors who trust Zutali Conmart",
      createFreeAccount: "Create Free Account",
      sustainableBadge: "Sustainable Construction Materials",
      productsCount: "products",
    },
    categories: {
      allCategories: "All Categories",
      filterBy: "Filter By",
      sortBy: "Sort By",
      priceRange: "Price Range",
      location: "Location",
      verified: "Verified Only",
      inStock: "In Stock Only",
      sortNewest: "Newest First",
      sortPriceLow: "Price: Low to High",
      sortPriceHigh: "Price: High to Low",
      sortPopular: "Most Popular",
      applyFilters: "Apply Filters",
      clearFilters: "Clear Filters",
      noProducts: "No products found",
      cementConcrete: "Cement & Concrete",
      steelMetal: "Steel & Metal",
      bricksBlocks: "Bricks & Blocks",
      timberWood: "Timber & Wood",
      roofing: "Roofing Materials",
      paintCoatings: "Paint & Coatings",
      plumbingPipes: "Plumbing & Pipes",
      electrical: "Electrical Materials",
    },
    quotation: {
      requestQuotation: "Request Quotation",
      quantity: "Quantity",
      message: "Message",
      deliveryLocation: "Delivery Location",
      sendRequest: "Send Request",
      quotationSent: "Quotation request sent successfully!",
    },
    review: {
      writeReview: "Write a Review",
      rating: "Rating",
      yourReview: "Your Review",
      submitReview: "Submit Review",
      reviewSubmitted: "Review submitted successfully!",
    },
    message: {
      messageSupplier: "Message Supplier",
      subject: "Subject",
      sendMessage: "Send Message",
      messageSent: "Message sent successfully!",
    },
    product: {
      details: "Product Details",
      specifications: "Specifications",
      description: "Description",
      reviews: "Reviews",
      supplier: "Supplier",
      requestQuote: "Request Quotation",
      addToFavorites: "Add to Favorites",
      shareProduct: "Share Product",
      inStock: "In Stock",
      outOfStock: "Out of Stock",
      verifiedSupplier: "Verified Supplier",
      rating: "Rating",
      noReviews: "No reviews yet",
      writeReview: "Write a Review",
    },
    auth: {
      loginTitle: "Login to Your Account",
      registerTitle: "Create Your Account",
      email: "Email Address",
      phone: "Phone Number",
      password: "Password",
      confirmPassword: "Confirm Password",
      fullName: "Full Name",
      businessName: "Business Name",
      forgotPassword: "Forgot Password?",
      rememberMe: "Remember Me",
      noAccount: "Don't have an account?",
      haveAccount: "Already have an account?",
      signUp: "Sign Up",
      signIn: "Sign In",
      orContinueWith: "Or continue with",
      asUserPurchaser: "As User/Purchaser",
      asProductOwner: "As Product Owner",
    },
    dashboard: {
      overview: "Overview",
      myQuotations: "My Quotations",
      myFavorites: "My Favorites",
      myReviews: "My Reviews",
      accountSettings: "Account Settings",
      verification: "Verification",
      subscription: "Subscription",
      totalQuotations: "Total Quotations",
      pendingQuotations: "Pending",
      approvedQuotations: "Approved",
      favoriteProducts: "Favorite Products",
      recentActivity: "Recent Activity",
      upgradeAccount: "Upgrade Account",
      verifyAccount: "Verify Account",
      currentPlan: "Current Plan",
      freePlan: "Free Plan",
      standardPlan: "Standard Plan",
      premiumPlan: "Premium Plan",
    },
    owner: {
      myProducts: "My Products",
      addProduct: "Add Product",
      quotationRequests: "Quotation Requests",
      businessProfile: "Business Profile",
      analytics: "Analytics",
      totalProducts: "Total Products",
      activeProducts: "Active",
      pendingApproval: "Pending Approval",
      totalViews: "Total Views",
      quotationsReceived: "Quotations Received",
      conversionRate: "Conversion Rate",
    },
    admin: {
      adminDashboard: "Admin Dashboard",
      userManagement: "User Management",
      productModeration: "Product Moderation",
      verificationRequests: "Verification Requests",
      reportedContent: "Reported Content",
      categoryManagement: "Category Management",
      totalUsers: "Total Users",
      verifiedUsers: "Verified Users",
      productOwners: "Product Owners",
      totalProducts: "Total Products",
      pendingVerification: "Pending Verification",
      reportedItems: "Reported Items",
    },
    footer: {
      companyDescription:
        "Ethiopia's premier marketplace for sustainable construction materials. Connecting builders with quality suppliers.",
      myAccount: "My Account",
      quickLinks: "Zutali",
      contactUs: "Contact Us",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      allRightsReserved: "All rights reserved",
      developedWith: "Developed with care for sustainable construction",
    },
    contact: {
      getInTouch: "Get in Touch",
      getInTouchDesc:
        "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
      yourName: "Your Name",
      yourEmail: "Your Email",
      subject: "Subject",
      message: "Message",
      sendMessage: "Send Message",
      contactInfo: "Contact Information",
      officeAddress: "Office Address",
      emailAddress: "Email Address",
      phoneNumber: "Phone Number",
    },
    about: {
      aboutUs: "About Us",
      ourMission: "Our Mission",
      ourMissionDesc:
        "To revolutionize the construction materials marketplace in Ethiopia by connecting quality suppliers with builders and contractors through a transparent, efficient, and sustainable platform.",
      ourVision: "Our Vision",
      ourVisionDesc:
        "To become the leading marketplace for construction materials in East Africa, promoting sustainable building practices and supporting local businesses.",
      whyChooseUs: "Why Choose Us",
      verifiedSuppliers: "Verified Suppliers",
      verifiedSuppliersDesc: "Every supplier on our platform is thoroughly verified to ensure quality and reliability.",
      competitivePricing: "Competitive Pricing",
      competitivePricingDesc: "Compare prices from multiple suppliers to get the best deals on construction materials.",
      sustainableFocus: "Sustainable Focus",
      sustainableFocusDesc: "We prioritize eco-friendly and sustainable construction materials for a better future.",
    },
  },
  am: {
    common: {
      home: "መነሻ",
      about: "ስለ እኛ",
      contact: "አግኙን",
      login: "ግባ",
      register: "ተመዝገብ",
      logout: "ውጣ",
      search: "ፈልግ",
      categories: "ምድቦች",
      products: "ምርቶች",
      dashboard: "ዳሽቦርድ",
      favorites: "ተወዳጆች",
      settings: "ቅንብሮች",
      profile: "መገለጫ",
      language: "ቋንቋ",
      english: "English",
      amharic: "አማርኛ",
      welcome: "እንኳን ወደ ዙታሊ ኮንማርት በደህና መጡ",
      loading: "በመጫን ላይ...",
      save: "አስቀምጥ",
      cancel: "ሰርዝ",
      delete: "ሰርዝ",
      edit: "አርትዕ",
      view: "ይመልከቱ",
      submit: "ላክ",
      back: "ተመለስ",
      next: "ቀጣይ",
      previous: "ቀዳሚ",
      close: "ዝጋ",
    },
    header: {
      searchPlaceholder: "የግንባታ ቁሳቁሶችን ይፈልጉ...",
      loginRegister: "ግባ / ተመዝገብ",
      asUser: "እንደ ተጠቃሚ",
      asOwner: "እንደ ምርት ባለቤት",
    },
    home: {
      heroTitle: "ህልምዎን ይገንቡ በ",
      heroTitleHighlight: "ጥራት ያላቸው ቁሳቁሶች",
      heroSubtitle:
        "የኢትዮጵያ ዋና የግንባታ ቁሳቁሶች ገበያ ገንቢዎችን፣ ተቋራጮችን እና አቅራቢዎችን የሚያገናኝ። የተረጋገጡ አቅራቢዎችን ያግኙ፣ ዋጋዎችን ያወዳድሩ እና ለሁሉም የግንባታ ፍላጎቶችዎ ግምት ያግኙ።",
      browseMaterials: "ቁሳቁሶችን ያስሱ",
      becomeSupplier: "አቅራቢ ይሁኑ",
      verifiedSuppliers: "የተረጋገጡ አቅራቢዎች",
      verifiedSuppliersDesc: "ሁሉም የምርት ባለቤቶች በትክክለኛ የንግድ ሰነዶች የተረጋገጡ ናቸው",
      qualityAssured: "የተረጋገጠ ጥራት",
      qualityAssuredDesc: "ዘላቂ እና ጥራት ያላቸው የግንባታ ቁሳቁሶች ብቻ ተዘርዝረዋል",
      deliveryOptions: "የማድረስ አማራጮች",
      deliveryOptionsDesc: "ብዙ አቅራቢዎች ወደ አካባቢዎ የማድረስ አገልግሎት ይሰጣሉ",
      bestPrices: "ምርጥ ዋጋዎች",
      bestPricesDesc: "ምርጡን ዋጋ ለማግኘት ከብዙ አቅራቢዎች ዋጋዎችን ያወዳድሩ",
      browseByCategory: "በምድብ ያስሱ",
      browseByCategoryDesc: "በምድብ የተደራጁ ሰፊ የግንባታ ቁሳቁሶቻችንን ያስሱ",
      viewAllCategories: "ሁሉንም ምድቦች ይመልከቱ",
      readyToStart: "ፕሮጀክትዎን ለመጀመር ዝግጁ ነዎት?",
      readyToStartDesc: "ዙታሊ ኮንማርትን የሚያምኑ በሺዎች የሚቆጠሩ ገንቢዎች እና ተቋራጮች ይቀላቀሉ",
      createFreeAccount: "ነፃ መለያ ይፍጠሩ",
      sustainableBadge: "ዘላቂ የግንባታ ቁሳቁሶች",
      productsCount: "ምርቶች",
    },
    categories: {
      allCategories: "ሁሉም ምድቦች",
      filterBy: "በ ማጣሪያ",
      sortBy: "በ ደርድር",
      priceRange: "የዋጋ ክልል",
      location: "አካባቢ",
      verified: "የተረጋገጡ ብቻ",
      inStock: "በመጋዘን ያሉ ብቻ",
      sortNewest: "አዲስ ከሆነ",
      sortPriceLow: "ዋጋ: ዝቅተኛ ወደ ከፍተኛ",
      sortPriceHigh: "ዋጋ: ከፍተኛ ወደ ዝቅተኛ",
      sortPopular: "በጣም ተወዳጅ",
      applyFilters: "ማጣሪያዎችን ተግብር",
      clearFilters: "ማጣሪያዎችን አጽዳ",
      noProducts: "ምንም ምርቶች አልተገኙም",
      cementConcrete: "ሲሚንቶ እና ኮንክሪት",
      steelMetal: "ብረት እና ብረታ ብረት",
      bricksBlocks: "ጡቦች እና ብሎኮች",
      timberWood: "እንጨት",
      roofing: "የጣሪያ ቁሳቁሶች",
      paintCoatings: "ቀለም እና ሽፋን",
      plumbingPipes: "የውሃ ቧንቧ",
      electrical: "የኤሌክትሪክ ቁሳቁሶች",
    },
    quotation: {
      requestQuotation: "ጥያቄ ይጠይቁ",
      quantity: "መጠን",
      message: "መልእክት",
      deliveryLocation: "የማድረሻ ቦታ",
      sendRequest: "ጥያቄ ላክ",
      quotationSent: "የጥያቄ ጥያቄ በተሳካ ሁኔታ ተልኳል!",
    },
    review: {
      writeReview: "ግምገማ ይጻፉ",
      rating: "ደረጃ",
      yourReview: "የእርስዎ ግምገማ",
      submitReview: "ግምገማ ላክ",
      reviewSubmitted: "ግምገማ በተሳካ ሁኔታ ተልኳል!",
    },
    message: {
      messageSupplier: "አቅራቢን መልእክት ላክ",
      subject: "ርዕስ",
      sendMessage: "መልእክት ላክ",
      messageSent: "መልእክት በተሳካ ሁኔታ ተልኳል!",
    },
    product: {
      details: "የምርት ዝርዝሮች",
      specifications: "ዝርዝሮች",
      description: "መግለጫ",
      reviews: "ግምገማዎች",
      supplier: "አቅራቢ",
      requestQuote: "ግምት ይጠይቁ",
      addToFavorites: "ወደ ተወዳጆች ጨምር",
      shareProduct: "ምርት አጋራ",
      inStock: "በስቶክ ውስጥ",
      outOfStock: "ከስቶክ ውጭ",
      verifiedSupplier: "የተረጋገጠ አቅራቢ",
      rating: "ደረጃ",
      noReviews: "ገና ምንም ግምገማዎች የሉም",
      writeReview: "ግምገማ ይጻፉ",
    },
    auth: {
      loginTitle: "ወደ መለያዎ ይግቡ",
      registerTitle: "መለያዎን ይፍጠሩ",
      email: "የኢሜይል አድራሻ",
      phone: "ስልክ ቁጥር",
      password: "የይለፍ ቃል",
      confirmPassword: "የይለፍ ቃል ያረጋግጡ",
      fullName: "ሙሉ ስም",
      businessName: "የንግድ ስም",
      forgotPassword: "የይለፍ ቃል ረሱ?",
      rememberMe: "አስታውሰኝ",
      noAccount: "መለያ የለዎትም?",
      haveAccount: "ቀድሞውኑ መለያ አለዎት?",
      signUp: "ተመዝገብ",
      signIn: "ግባ",
      orContinueWith: "ወይም ይቀጥሉ በ",
      asUserPurchaser: "እንደ ተጠቃሚ",
      asProductOwner: "እንደ ምርት ባለቤት",
    },
    dashboard: {
      overview: "አጠቃላይ እይታ",
      myQuotations: "የእኔ ግምቶች",
      myFavorites: "የእኔ ተወዳጆች",
      myReviews: "የእኔ ግምገማዎች",
      accountSettings: "የመለያ ቅንብሮች",
      verification: "ማረጋገጫ",
      subscription: "ምዝገባ",
      totalQuotations: "ጠቅላላ ግምቶች",
      pendingQuotations: "በመጠባበቅ ላይ",
      approvedQuotations: "የጸደቁ",
      favoriteProducts: "ተወዳጅ ምርቶች",
      recentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
      upgradeAccount: "መለያ አሻሽል",
      verifyAccount: "መለያ አረጋግጥ",
      currentPlan: "የአሁኑ እቅድ",
      freePlan: "ነፃ እቅድ",
      standardPlan: "መደበኛ እቅድ",
      premiumPlan: "ፕሪሚየም እቅድ",
    },
    owner: {
      myProducts: "የእኔ ምርቶች",
      addProduct: "ምርት ጨምር",
      quotationRequests: "የግምት ጥያቄዎች",
      businessProfile: "የንግድ መገለጫ",
      analytics: "ትንታኔዎች",
      totalProducts: "ጠቅላላ ምርቶች",
      activeProducts: "ንቁ",
      pendingApproval: "ፈቃድ በመጠባበቅ ላይ",
      totalViews: "ጠቅላላ እይታዎች",
      quotationsReceived: "የተቀበሉ ግምቶች",
      conversionRate: "የልወጣ መጠን",
    },
    admin: {
      adminDashboard: "የአስተዳዳሪ ዳሽቦርድ",
      userManagement: "የተጠቃሚ አስተዳደር",
      productModeration: "የምርት ቁጥጥር",
      verificationRequests: "የማረጋገጫ ጥያቄዎች",
      reportedContent: "የተዘገበ ይዘት",
      categoryManagement: "የምድብ አስተዳደር",
      totalUsers: "ጠቅላላ ተጠቃሚዎች",
      verifiedUsers: "የተረጋገጡ ተጠቃሚዎች",
      productOwners: "የምርት ባለቤቶች",
      totalProducts: "ጠቅላላ ምርቶች",
      pendingVerification: "ማረጋገጫ በመጠባበቅ ላይ",
      reportedItems: "የተዘገቡ ንጥሎች",
    },
    footer: {
      companyDescription: "የኢትዮጵያ ዋና የዘላቂ የግንባታ ቁሳቁሶች ገበያ። ገንቢዎችን ከጥራት አቅራቢዎች ጋር ማገናኘት።",
      myAccount: "የእኔ መለያ",
      quickLinks: "ዙታሊ",
      contactUs: "አግኙን",
      privacyPolicy: "የግላዊነት ፖሊሲ",
      termsOfService: "የአገልግሎት ውሎች",
      allRightsReserved: "መብቱ በህግ የተጠበቀ ነው",
      developedWith: "ለዘላቂ ግንባታ በጥንቃቄ የተሰራ",
    },
    contact: {
      getInTouch: "ያግኙን",
      getInTouchDesc: "ጥያቄዎች አሉዎት? ከእርስዎ መስማት እንፈልጋለን። መልእክት ይላኩልን እና በተቻለ ፍጥነት እንመልሳለን።",
      yourName: "ስምዎ",
      yourEmail: "ኢሜልዎ",
      subject: "ርዕስ",
      message: "መልእክት",
      sendMessage: "መልእክት ላክ",
      contactInfo: "የመገኛ መረጃ",
      officeAddress: "የቢሮ አድራሻ",
      emailAddress: "የኢሜይል አድራሻ",
      phoneNumber: "ስልክ ቁጥር",
    },
    about: {
      aboutUs: "ስለ እኛ",
      ourMission: "የእኛ ተልዕኮ",
      ourMissionDesc:
        "በኢትዮጵያ ውስጥ የግንባታ ቁሳቁሶች ገበያን በግልጽ፣ በብቃት እና በዘላቂነት መድረክ ጥራት ያላቸውን አቅራቢዎች ከገንቢዎች እና ተቋራጮች ጋር በማገናኘት አብዮት ማድረግ።",
      ourVision: "የእኛ ራዕይ",
      ourVisionDesc: "በምስራቅ አፍሪካ ዋና የግንባታ ቁሳቁሶች ገበያ መሆን፣ ዘላቂ የግንባታ ልምዶችን ማስተዋወቅ እና የአካባቢ ንግዶችን መደገፍ።",
      whyChooseUs: "ለምን እኛን ይምረጡ",
      verifiedSuppliers: "የተረጋገጡ አቅራቢዎች",
      verifiedSuppliersDesc: "በመድረካችን ላይ ያለ እያንዳንዱ አቅራቢ ጥራት እና አስተማማኝነትን ለማረጋገጥ በደንብ ተረጋግጧል።",
      competitivePricing: "ተወዳዳሪ ዋጋ",
      competitivePricingDesc: "በግንባታ ቁሳቁሶች ላይ ምርጡን ዋጋ ለማግኘት ከብዙ አቅራቢዎች ዋጋዎችን ያወዳድሩ።",
      sustainableFocus: "ዘላቂ ትኩረት",
      sustainableFocusDesc: "ለተሻለ ወደፊት ለአካባቢ ተስማሚ እና ዘላቂ የግንባታ ቁሳቁሶችን እንቀድማለን።",
    },
  },
}
